---

#
# Generic tasks that we always want to happen, regardless
# if the user wants nextcloud-nginx-proxy or not.
#
# If the user would set up their own nginx proxy server,
# the config files from nextcloud-nginx-proxy can be reused.
#
# It doesn't hurt to put them in place, even if they turn out
# to be unnecessary.
#
- name: Ensure Nextcloud nginx-proxy paths exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: root
    group: root
  with_items:
    - "{{ nextcloud_nginx_proxy_data_path }}"
    - "{{ nextcloud_nginx_proxy_confd_path }}"

- name: Ensure Nextcloud proxy vhost configured
  template:
    src: "{{ role_path }}/templates/nginx-conf.d/{{ item }}.j2"
    dest: "{{ nextcloud_nginx_proxy_confd_path }}/{{ item }}"
    mode: 0644
  with_items:
    - "nextcloud-apache.conf"

#
# Tasks related to setting up nextcloud-nginx-proxy
#
- name: Ensure nginx Docker image is pulled
  docker_image:
    name: "{{ nextcloud_nginx_proxy_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
  when: nextcloud_nginx_proxy_enabled|bool

- name: Ensure nextcloud-nginx-proxy.service installed
  template:
    src: "{{ role_path }}/templates/systemd/nextcloud-nginx-proxy.service.j2"
    dest: "/etc/systemd/system/nextcloud-nginx-proxy.service"
    mode: 0644
  when: nextcloud_nginx_proxy_enabled|bool

- name: Ensure periodic restarting of nextcloud-nginx-proxy is configured (for SSL renewal)
  template:
    src: "{{ role_path }}/templates/cron.d/nextcloud-nginx-proxy-periodic-restarter.j2"
    dest: "/etc/cron.d/nextcloud-nginx-proxy-periodic-restarter"
    mode: 0600
  when: nextcloud_nginx_proxy_enabled|bool

#
# Tasks related to getting rid of nextcloud-nginx-proxy (if it was previously enabled)
#

- name: Check existence of nextcloud-nginx-proxy service
  stat: path="/etc/systemd/system/nextcloud-nginx-proxy.service"
  register: nextcloud_nginx_proxy_service_stat

- name: Ensure nextcloud-nginx-proxy is stopped
  service: name=nextcloud-nginx-proxy state=stopped daemon_reload=yes
  register: stopping_result
  when: "not nextcloud_nginx_proxy_enabled and nextcloud_nginx_proxy_service_stat.stat.exists"

- name: Ensure nextcloud-nginx-proxy.service doesn't exist
  file:
    path: "/etc/systemd/system/nextcloud-nginx-proxy.service"
    state: absent
  when: "not nextcloud_nginx_proxy_enabled and nextcloud_nginx_proxy_service_stat.stat.exists"

- name: Ensure periodic restarting of nextcloud-nginx-proxy is removed
  file:
    path: "/etc/cron.d/nextcloud-nginx-proxy-periodic-restarter"
    state: absent
  when: "not nextcloud_nginx_proxy_enabled"
